### ISSUE TITLE
Does it work on Mac?

### ISSUE THREAD

**Issue by Lootoholic** [RoboCoachTechnologies/GPT-Synthesizer#1]
If I want to run it in a terminal on my Mac, is there anything that I need to do beforehand?

**Comment by RoboCoachTech** [comment]
In order to install GPT Synthesizer on MacOS, you need to have pip installed.
Here is how to download and install pip:

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py

now you are good to go!
