### ISSUE TITLE
Install on Mac

### ISSUE THREAD

**Issue by Lootoholic** [RoboCoachTechnologies/GPT-Synthesizer#1]
Does it work on Mac? Do I need to install anything before that?

**Comment by saeedshamshiri** [comment]
Make sure you have pip installed on your Mac. 
You can download pip by typing the following command in your Mac Terminal:

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

Then you can install pip:

python3 get-pip.py

Now you should be able to install GPT Synthesizer

**Comment by Lootoholic** [comment]
Thanks. I'll give it a go.
