### ISSUE TITLE
Color coded output?

### ISSUE THREAD

**Issue by Lootoholic** [RoboCoachTechnologies/GPT-Synthesizer#2]
Is it possible to have the output on the terminal color coded? For example, any text that I type be in black while the AI's answer in blue?

**Comment by RoboCoachTech** [comment]
Thank you for your feedback.
Currently the generated text is only in the default color (e.g. black text on a white background). We will look into color coding the output in our future releases.

**Comment by saeedshamshiri** [comment]
The streamlit GUI addresses this issue. Now the user inputs are visually differentiated from the AI's text.
