### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by radman-x** [RoboCoachTechnologies/GPT-Synthesizer#5]
What is the status of this most promising project? Most of the recent commits have been just readme updates. Your roadmap shows some interesting new features but the readme just says the project "will be actively maintained" -- is there any active new development underway or is it just in a maintenance mode?

**Comment by saeedshamshiri** [comment]
Right now, we are working on giving it a graphic user interface to make it more visually appealing, and to implement some quality of life features. Everything in the roadmap will be implemented sooner or later, and more features will be added which are not showing in the roadmap.

**Comment by radman-x** [comment]
Ok, thnx for update
